# Generated by Django 4.2.1 on 2023-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(null=True, upload_to="logos/"),
        ),
    ]
