# Generated by Django 4.2.1 on 2023-06-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_ad_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "Объявление", "verbose_name_plural": "Объявления"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
